version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysqldata:/var/lib/mysql

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  auth-service:
    build: ./auth-service
    container_name: auth_service
    restart: always
    ports:
      - "5001:5001"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_NAME: microservice_db
      JWT_SECRET: supersecret
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      - mysql
      - rabbitmq

  user-service:
    build: ./user-service
    container_name: user_service
    restart: always
    ports:
      - "5002:5002"
    environment:
      DB_HOST: postgres 
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: users
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq

volumes:
  pgdata:
  mysqldata:
