spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: postgres
    password: Tuanga@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 5003
