spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/orders
  #   url: jdbc:postgresql://localhost:5433/orders
  #   username: postgres
  #   password: Tuanga@123
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 5003

jwt:
  secret: fasdfasdfawf12345678901234567890
