spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/productDB
      auto-index-creation: true
  main:
    allow-circular-references: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 5004

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: fasdfasdfawf12345678901234567890
