spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/productDB
      auto-index-creation: true
  main:
    allow-circular-references: true
server:
  port: 5003

logging:
  level:
    org:
      springframework:
        security: DEBUG
