# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product
    username: postgres
    password: Tuanga@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # ===============================
  # RABBITMQ
  # ===============================
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      mandatory: true
# ===============================
# SERVER
# ===============================
server:
  port: 5004

# ===============================
# LOGGING
# ===============================
logging:
  level:
    org:
      springframework:
        security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

# ===============================
# JWT CONFIG
# ===============================
jwt:
  secret: fasdfasdfawf12345678901234567890
  expiration: 3600000
